appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: M7O8I3P5zPFVq6t9sPAE6Wu5bOZ4pIQDshhqhSq7UbSPT6rKv55NzudL8YZkCE30pHzraBC4AW395+svG9R3Tb+Ck1pASiubtflG6oxdTIoRXU+7wtHntRxbf5P5oGuefGP50gzaCYawj6hWGRX4vcRS7RhuGHVr0SaJ7RI4OtQPN655Pz5pnsl8UP1isEgmRTE9sQSDSgIVbgN6HxCZZPh4IsG84utSBrlFiOT3h+CAe498yBR5Bq2n60qggilL1Xrzm0oX4I9LGubNNpApGLid7fnpEvuHeLwgQ+aye/HW3K1LbP8RTKNk8a/gTDwi0pTsdQTJreIjKFrW9/DIIkdR6t7M67YnGhFhDrtnqFKv0XLYJk8Lu9FEzpOtn+IjHvB8daftr+/Jluyxj+wV9J1w8Trx3jJyJKJbHvCzlKzrthc/4L21Ob87DxKaWU3NscCUXTCz8/wW2Qv/TqKO8re55wb5HB58iqBbfa7OWfxiorL51gkPAp28KV/KJ7jks1Ow34WvrKL32pdF1nVwTUuTlr+inoHDAoDaqNTa8SxtoF3vZE6pB4RdX2nPlu0epYRHOwWb0GI6bdrjrKY5dYe1ZanDGkf0HGkZcoXzEdpR0bISTYN+NwtHsb62LOM1uskVU8FxMLE6xdhjUx1YkfvMnmdQ/CXm4Mf6xcLxw+A=
